### PR TITLE
Add implementation for `sqrt_ratio_i()`

### PR DESCRIPTION
**Pull request by AiyionPrime**
> in dalek-ff-group

`cargo fmt` and `clippy` are silent,
tests are fine.

Had no need for `conditional_negate` so I left it out for now, might add it later.

> Shouldn't that be a CtOption though?

_Originally posted by @kayabaNerve in https://github.com/dalek-cryptography/curve25519-dalek/issues/389#issuecomment-1212682725_

This matches the function definition of curve25519-dalek, so it returns `(Choice, FieldElement)`.

I haven't seen a conflicting Trait that specifies it to be `CtOption`.

### CODE REVIEW

**Comment by kayabaNerve** [comment]
Hey! Sorry for the delay in reviewing this.

Was there a reason to take it in by borrow? It's copied around a bunch regardless and should be sufficiently small we can perform that lint as a nicety.

Algorithm looks great :+1: Thanks for the submission.

**Comment by AiyionPrime** [comment]
> Was there a reason to take it in by borrow?

Not from functionalities perspective, just to match the *exact* fn-definition curve25519-dalek has, but I can change that.

**Comment by kayabaNerve** [comment]
Would be appreciated, unless that specific property is desired, yet I'm happy to do lint myself too :p Don't mean to force you into it ;)

**Comment by AiyionPrime** [comment]
No problem, will do.
I'll get to it in the afternoon.

**Comment by AiyionPrime** [comment]
resolved in b95dd5eb41c3323561135136245a7bd005221a5c

**Comment by AiyionPrime** [comment]
Tests, fmt and clippy are good.

**Comment by kayabaNerve** [comment]
Thanks :D Definitely good to have.

**Pull request merged**
