### PR TITLE
README.md: Add links to Reddit, Telegram and Website

### PR DESCRIPTION
**Pull request by Steven-Chang**

### CODE REVIEW

**Comment by kayabaNerve** [comment]
That isn't our Telegram. Someone else made it when Serai was announced. While they offered ownership to me, at the time I was unsure if I wanted to commit to a Telegram. Now, I feel like I should've accepted it at least to squat the URL... I'll reach out to the owner who offered to transfer it.

This doesn't change my lack of desire to commit to a Telegram, and without that, I don't care to advertise it/promote it.

**Comment by Steven-Chang** [comment]
No problems. I'll just leave this here in case the owner of the Telegram group hands it over to you.

**Comment by monerobull** [comment]
Petition to use !SeraiDEX@monero.town instead of a subreddit 😋

**Comment by kayabaNerve** [comment]
I did reach out to the admin and have been unable to get in contact thus far :/

**Comment by Steven-Chang** [comment]
Start a new one?

**Comment by Steven-Chang** [comment]
Rebased and conflict resolved now that Telegram group has been sorted.

**Comment by kayabaNerve** [comment]
1) The Reddit link is to a thread on the subreddit, not the subreddit.
2) Mind reverting the alpha-sorting for the Feed/Chat sorting, please? Though I'll note the website/Immunefi should likely be first.

**Comment by Steven-Chang** [comment]
> 1. The Reddit link is to a thread on the subreddit, not the subreddit.
> 2. Mind reverting the alpha-sorting for the Feed/Chat sorting, please? Though I'll note the website/Immunefi should likely be first.

- Reddit link updated.
- Website and Immunefi links put first. Order of other links preserved. Reddit and Telegram links put on end.

**Comment by kayabaNerve** [comment]
Thank you :)

**Pull request merged**
