### PR TITLE
coordinator/src/db.rs db macro implimentation

### PR DESCRIPTION
**Pull request by econsta**

### CODE REVIEW

**Comment by kayabaNerve** [comment]
```
[2023-11-15T15:33:25Z DEBUG serai_coordinator] publishing transaction dedb43c6f999939a9db20274f1b653d528e44b04b3552a06fb82fa4551238a5c
thread 'tokio-runtime-worker' panicked at coordinator/src/db.rs:89:82:
called `Result::unwrap()` on an `Err` value: Custom { kind: Other, error: "invalid transaction type" }
```

CI failures seem to be due to the PR.

Let me know if you want help finding where the discrepancy is :) Thanks for moving this over :D

**Comment by econsta** [comment]
I might need some help figuring out what is going wrong

**Comment by kayabaNerve** [comment]
Happy to help take a look. The two tests failings may be the ones I just borked if you're off the most recent develop (absolutely my bad. PR runs worked but the code isn't overall stable enough. I'm debating reverting it...).

**Comment by kayabaNerve** [comment]
Hm. coordinator key_gen failed which should execute regardless of my most recent changes. There may be some message prior stored in the DB which is no longer getting communicated... Will investigate deeper when I have a moment.

**Comment by kayabaNerve** [comment]
Rebased, with no effort to fix any bugs prior present. I just need the rebase to understand what changes are up here and start correcting any errors.

**Comment by kayabaNerve** [comment]
CI passed for "Misc tweaks", referring to correcting the rebase, yet I had a local test failure for "Minor tweaks", referring to nits I wanted to do before merging the PR.

I had the Batch test fail, so I'd assume it to fail for the CI too... I either broke something in my most recent commit or something's unstable.

**Comment by kayabaNerve** [comment]
I'm guessing some unstability. That commit is quite minor...

EDIT: #475

**Comment by kayabaNerve** [comment]
Thanks :)

**Pull request merged**
