### PR TITLE
Creation of new Debian 12 guide for installation of validator 

### PR DESCRIPTION
**Pull request by bennyb0y**
Created a new document to describe the process of installing and operating a dev node validator. This guide is geared to Debian 12.5.0 but may work with others. Not sure where this guide might best live, so I will leave it here for now. 

Removed some redundant commands from the original Getting started.md

### CODE REVIEW

**Comment by kayabaNerve** [comment]
Why close this? I'd be interested in getting it merge-able.

**Comment by bennyb0y** [comment]
Happy to merge. I just need access.

**Comment by bennyb0y** [comment]
Screenshot 2024-02-26 at 11 46 53

**Comment by kayabaNerve** [comment]
Sorry it's taken me so long to look/review/polish. I'll try to do so over the next week or so.

FYI, the merge button is on my end, not on yours :sweat_smile:

**Comment by kayabaNerve** [comment]
Distinct note: It may make sense to fold this into the newly added `docs/` folder (old one was moved to `spec/`).

**Pull request closed without merging**
