### PR TITLE
Experimental Dockerfile support

### PR DESCRIPTION
**Pull request by yatima1460**
`docker build --tag serai .`

For now running it just prints the version, needs arguments and ports!

### CODE REVIEW

**Comment by kayabaNerve** [comment]
Hey! Great to see you again :D Thanks for submitting this.

I know https://github.com/substrate-developer-hub/substrate-node-template offers some level of Docker code, which may be relevant.

I did just remove the requirements on building Monero. It's something I missed when doing #30 which should help here with both amount of dependencies and build time. I unfortunately think most of that is from Substrate though, which isn't something we can do anything about.

But yes, it still requires git in order to populate monero/. Specifically, as of right now, it uses a submodule and I'm not even sure that'll work if packaged under Cargo. I believe the current submodule will need to replaced with a git clone for that, and I don't have a better idea for packaging it at this time. This requirement will likely stand until we replace all C functions with Rust, as noted in #31 and #32.

We should work with stable Rust, only using nightly for wasm.

I... didn't know about the clang requirement? We don't grab clang for the CI? I'm not saying it isn't needed, as it may come shipped with Ubuntu/Ubuntu's build-essential and not Debian, but that'd be very surprising. Not an issue to simply include it here and call it a day though.

Regarding the `.dockerignore`... does this count as a source/binary distribution when packaged? It seems like the Dockerfile grabs this source distribution (the repo itself) to create a binary distribution it fully packages. That should preserve the AGPL license and we'd also have to include at least the GPL 3.0 due to Substrate's licensing. Then we'd have to review Apache 2.0/MIT requirements (if we ever actually published the built Docker image).

It's bullshit like that why I just stripped Docker for now, as we don't have any nodes being deployed for testing. Protonet will have that though, and this is a solid base we can use then, so thank you for it :)

**Comment by yatima1460** [comment]
Yes GitHub Actions already comes with Clang preinstalled!

Here you can check the lists!

https://github.com/actions/virtual-environments/blob/main/images/linux/Ubuntu2204-Readme.md

**Comment by kayabaNerve** [comment]
That'd explain it :) Thanks for clarifying.

**Comment by yatima1460** [comment]
The best way probably would be to build Monero Docker image and then push it to GitHub Container Registry and use that as a cached artifact for other images

**Comment by yatima1460** [comment]
Generally I never use the GitHub Actions jobs as "raw" unless creating a Docker image is prohibitive 

Because they are never portable and replicating the build process on a local machine becomes painful

**Comment by yatima1460** [comment]
Also another good advantage of having a perfect Docker image is that it behaves like build instructions and a dependencies documentation 😄

**Comment by kayabaNerve** [comment]
If we're discussing Monero packaging, my consideration was about the Rust crate. Grabbing a Docker image doesn't help when that needs source :p

If we're discussing Monero daemon packaging, for testing purposes, this would matter if we moved the CI over to Docker. I... wouldn't be against that? Except I did just manage to get GH Actions setup lol. So I'd be curious to see the benefit.

If we're discussing Monero packaging for release purposes, where Serai validators need a Serai node and a Monero node, we'll likely want a Kubernetes + Docker structure there.

I definitely appreciate having a dependencies/build document available, which these do serve as a literal version of. I don't think I even comment a regtest daemon is needed to run the Monero tests at this point in time, when I definitely should... Currently working on getting more Serai protocol docs up though.

Want to reach out on Matrix/Discord so we can talk more there? :D I'll add links to the README since apparently I've forgotten to.

**Comment by kayabaNerve** [comment]
@TheArchitect108 brought up merging this. To highlight the steps required:

- .dockerignore canonical to .gitignore
- Including licensing as needed, related to #13 (for now, just not excluding the AGPL)

- Correct #TODO for # TODO, which is minor and will be in #77 
- newline before EOF, which will be in #77 
- No double lines, which is in #77 

- Use stable Rust
- Remove git and the Monero dependencies (which were required when this PR was made)

- Replace FIXME with TODO, for specifying a clang version, though I don't actually care to nitpick to such a degree and rather remove that note entirely. While it may be nice to have a firm knowledge of the required clang version, that's a RocksDB decision where we follow their lead
- Actually run Serai, I guess in the dev mode for now

**Comment by TheArchitect108** [comment]
Thanks for the contribution, closing this out as it was covered in #114. Happy to coordinate on further work, feel free to ping me on discord.

**Pull request closed without merging**
